# Generated by Django 4.0.3 on 2022-06-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_image_post_intruder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intruder_image',
            field=models.ImageField(upload_to='intruder_image/%Y/%m/%d/'),
        ),
    ]
