# Generated by Django 4.0.3 on 2022-06-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_intruder_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='intruder_image',
            new_name='image',
        ),
    ]
