# Generated by Django 4.0.3 on 2022-06-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='intruder_image',
        ),
    ]
